name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.407
    - name: Restore dependencies
      run: ls -a && dotnet restore
      working-directory: ./Example
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./Example
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./Example
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.5
      with:
        projectBaseDir: ./Example
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
